require "spec"
require "../src/1/main.cr"
require "../src/2/main.cr"
require "../src/3/main.cr"
require "../src/4/main.cr"
require "../src/5/main.cr"
require "../src/6/main.cr"
require "../src/7/main.cr"
require "../src/8/main.cr"
require "../src/9/main.cr"

require "../src/common.cr"
